using MemoAna.Domain.Matchmaking;

namespace MemoAna.Domain.Sessions;

/// <summary>
/// Represents an intent submitted to the authoritative match session.
/// </summary>
/// <param name="CommandId">The client- or server-generated command identifier.</param>
/// <param name="Player">The player associated with the command, or <see langword="null"/> for a system command.</param>
/// <param name="ClientSequence">The client sequence associated with the command.</param>
/// <remarks>
/// Commands contain intent and identity metadata only. Authoritative outcomes are derived by the session.
/// </remarks>
public abstract record SessionCommand(string CommandId, PlayerIdentity? Player, ulong ClientSequence)
{
    /// <summary>
    /// Gets a value indicating whether the command is generated by the server rather than a player.
    /// </summary>
    public bool IsSystemCommand => Player is null;
}

/// <summary>
/// Requests that a player join the session.
/// </summary>
/// <param name="CommandId">The command identifier.</param>
/// <param name="JoiningPlayer">The player identity assigned to the joining player.</param>
/// <param name="ClientSequence">The first client sequence value for the player.</param>
public sealed record JoinSessionCommand(
    string CommandId,
    PlayerIdentity JoiningPlayer,
    ulong ClientSequence = 1)
    : SessionCommand(CommandId, JoiningPlayer, ClientSequence);

/// <summary>
/// Requests a readiness-state change for a player.
/// </summary>
/// <param name="CommandId">The command identifier.</param>
/// <param name="PlayerId">The player changing readiness.</param>
/// <param name="Ready">The requested readiness state.</param>
/// <param name="ClientSequence">The player's client sequence value.</param>
public sealed record ReadyUpCommand(
    string CommandId,
    PlayerIdentity PlayerId,
    bool Ready,
    ulong ClientSequence)
    : SessionCommand(CommandId, PlayerId, ClientSequence);

/// <summary>
/// Requests that the authoritative session start.
/// </summary>
/// <param name="CommandId">The server-generated command identifier.</param>
public sealed record StartGameCommand(string CommandId)
    : SessionCommand(CommandId, null, 0);

/// <summary>
/// Requests that a player leave the session.
/// </summary>
/// <param name="CommandId">The command identifier.</param>
/// <param name="PlayerId">The player leaving the session.</param>
/// <param name="Reason">The reason for leaving.</param>
/// <param name="ClientSequence">The player's client sequence value.</param>
public sealed record LeaveSessionCommand(
    string CommandId,
    PlayerIdentity PlayerId,
    LeaveReason Reason,
    ulong ClientSequence)
    : SessionCommand(CommandId, PlayerId, ClientSequence);

/// <summary>
/// Requests that a player flip an unflipped board position.
/// </summary>
/// <param name="CommandId">The command identifier.</param>
/// <param name="PlayerId">The player making the move.</param>
/// <param name="Position">The zero-based board position.</param>
/// <param name="ClientSequence">The player's client sequence value.</param>
public sealed record FlipCardCommand(
    string CommandId,
    PlayerIdentity PlayerId,
    int Position,
    ulong ClientSequence)
    : SessionCommand(CommandId, PlayerId, ClientSequence);

/// <summary>
/// Requests that the authoritative session be aborted.
/// </summary>
/// <param name="CommandId">The server-generated command identifier.</param>
public sealed record AbortSessionCommand(string CommandId)
    : SessionCommand(CommandId, null, 0);

/// <summary>
/// Requests that the authoritative session be expired.
/// </summary>
/// <param name="CommandId">The server-generated command identifier.</param>
public sealed record ExpireSessionCommand(string CommandId)
    : SessionCommand(CommandId, null, 0);
